### ISSUE TITLE
Make enter the default for info

### ISSUE THREAD

**Issue by chanders** [pix/aeon#48]
More like boxee. That way you press enter for info and then play from there. This thread sums it up nicely. I can be done and has been done by Alaska Revisited. Works great there..

http://forum.xbmc.org/showthread.php?t=76699

**Comment by mindweaver** [comment]
This will never happen as default. Mainly because it is annoying. When you play a movie you want to play it. not press an extra time just to get it started. Why even have this when there is a perfectly nice info button om the remote?

Enough of my dislike :) If someone wants to build it, I guess it will have to be added with an option to turn it on/off.

**Comment by chanders** [comment]
You guys seem to really like using a remote ;) I use the keyboard myself. What remote do you use?

**Comment by mindweaver** [comment]
The keyboard works fine for info aswell :) just hit i. 

I use a Logitech Harmony 525. it's fantastic for navigating XBMC and my entire setup.

**Comment by sergiocos** [comment]
The info must be optional. I believe that most users ALREADY know what that movie is about (that's why we gonna watch the damn thing). So no need for foreplay, we don't like it anyway! :)

**Comment by pix** [comment]
Closing as this does't seems to be wanted anymore
